[project]
name = "music-teacher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Anton", email = "code.antonsov8@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
music-teacher = "music_teacher:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
